name: Manual Workflow

# 수동 트리거 설정
on:
  workflow_dispatch:

jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello from GitHub Actions!"
      - name: Print date
        run: date
      - name: Print uname -a
        run: uname -a
      - name: Print date and uname
        run: |
              date
              uname -a
              echo "print date and uname"
